/* Autogenerated by png2wx.pl on Thu May  1 11:32:28 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_weatherfax;

#endif /* ICONS_H */
